#!/bin/bash

# Lista de libros basada en los datos proporcionados
books=(
  "genesis"
  "exodo"
  "levitico"
  "numeros"
  "deuteronomio"
  "josue"
  "jueces"
  "rut"
  "1-samuel"
  "2-samuel"
  "1-reyes"
  "2-reyes"
  "1-cronicas"
  "2-cronicas"
  "esdras"
  "nehemias"
  "ester"
  "job"
  "salmos"
  "proverbios"
  "eclesiastes"
  "cantares"
  "isaias"
  "jeremias"
  "lamentaciones"
  "ezequiel"
  "daniel"
  "oseas"
  "joel"
  "amos"
  "abdias"
  "jonas"
  "miqueas"
  "nahum"
  "habacuc"
  "sofonias"
  "hageo"
  "zacarias"
  "malaquias"
  "mateo"
  "marcos"
  "lucas"
  "juan"
  "hechos"
  "romanos"
  "1-corintios"
  "2-corintios"
  "galatas"
  "efesios"
  "filipenses"
  "colosenses"
  "1-tesalonicenses"
  "2-tesalonicenses"
  "1-timoteo"
  "2-timoteo"
  "tito"
  "filemon"
  "hebreos"
  "santiago"
  "1-pedro"
  "2-pedro"
  "1-juan"
  "2-juan"
  "3-juan"
  "judas"
  "apocalipsis"
)

echo "Consultando el primer capítulo de cada libro de la Biblia (Reina Valera 1960):"
echo "================================================================================="

for book in "${books[@]}"; do
  echo ""
  echo "Libro: $book"
  echo "URL: https://bible-api.deno.dev/api/read/rv1960/$book/1"
  response=$(curl -s "https://bible-api.deno.dev/api/read/rv1960/$book/1")
  text=$(echo "$response" | jq -r '.text' 2>/dev/null)
  if [ $? -eq 0 ] && [ "$text" != "null" ]; then
    echo "Texto: $text"
  else
    echo "Error al obtener texto o respuesta inválida: $response"
  fi
  echo "---------------------------------------------------------------------------------"
done